name: Test

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Get dependencies
        run: make tidy

      - name: Test code
        run: go test -v .